### ISSUE TITLE
Error Exception in AddRemoveACTIONS

### ISSUE THREAD

**Issue by GrandNuageDeMagellan** [zrisher/GardenPerformance#32]
[2015-09-25 23:33:50,304][Error][Main][UpdateManager][Static][Update] - Exception in AddRemoveActions: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at SEGarden.Logic.UpdateManager.<>c__DisplayClass8.<RegisterEntityComponentConstructorInternal>b__7(IMyEntity e)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SEGarden.Logic.UpdateManager.RegisterEntityComponentConstructorInternal(Action`1 constructor, MyObjectBuilderType entityType, RunLocation targetLocation)
   at SEGarden.Logic.UpdateManager.<>c__DisplayClass5.<RegisterEntityComponent>b__4()
   at SEGarden.Threading.LockedQueue`1.DequeueAll(Action`1 invoke)
   at SEGarden.Logic.UpdateManager.Update()

**Comment by zrisher** [comment]
Hmm probably related to #33 looks like your player didn't get added for some reason. Could be due to changes in ModAPI, there were a ton yesterday and today.
